namespace: fe-dev
domain: sberautotech.dev.fe.sbauto.tech
service_account: fe-dev-sa

cert_issuer: infra-vault
cert_secret: sberautotech-dev-fe-sbauto

replicas: 1

requests:
  cpu: '50m'
  memory: '50Mi'
