---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ domain }}
  namespace: {{ namespace }}
spec:
  secretName: {{ cert_secret }}
  issuerRef:
    name: {{ cert_issuer }}
  commonName: {{ domain }}
  dnsNames:
    - {{ domain }}
