---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ app_name }}-{{ package_name }}
  name: {{ app_name }}-{{ package_name }}
  namespace: {{ namespace }}
data:
    nginx-conf: |
      server {
          listen 8000;

          server_name site;
          charset utf-8;

          gzip on;
          gzip_disable "msie6";
          gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

          location / {
              root   /usr/share/nginx/html;
              try_files $uri /index.html;
          }
      }
