---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ app_name }}-{{ package_name }}
  name: {{ app_name }}-{{ package_name }}
  namespace: {{ namespace }}
data:
    nginx-conf: |
{% if stand == 'dev' %}
      resolver 10.10.0.162 10.10.0.41;

      server {
          listen {{ service_port }};

          server_name site;
          charset utf-8;

          gzip on;
          gzip_disable "msie6";
          gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;

          location / {
              root   /usr/share/nginx/html;
              try_files $uri $uri/index.html /index.html;
          }

          location /form {
              proxy_pass https://sberautotech-backend.dev.fe.sbauto.tech;
          }
      }
{% endif %}

{% if stand == 'infra' %}
      server {
        listen {{ service_port }};
        return 302 https://sberautotech.com;
      }
{% endif %}
