---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ app_name }}-{{ package_name }}
    version: {{ app_version }}
  name: {{ app_name }}-{{ package_name }}
  namespace: {{ namespace }}
spec:
  progressDeadlineSeconds: {{ deploy_timeout }}
  replicas: {{ replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ app_name }}-{{ package_name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ app_name }}-{{ package_name }}
    spec:
      securityContext:
        runAsUser: 101
      containers:
        - name: {{ app_name }}-{{ package_name }}
          image: "{{ docker_registry }}/{{ package_name }}:{{ app_version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ service_port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ requests.cpu }}
              memory: {{ requests.memory }}
        volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-conf
            subPath: default.conf
      imagePullSecrets:
        - name: {{ image_pull_secret }}
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ app_name }}-{{ package_name }}
            defaultMode: 420
            items:
              - key: nginx-conf
                path: default.conf
      restartPolicy: Always
      serviceAccount: {{ service_account }}
