---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{% if cert_issuer == 'infra-letsencrypt' %}
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: {{ cert_issuer }}
    konghq.com/https-redirect-status-code: "301"
    konghq.com/protocols: https
{% endif %}
    kubernetes.io/ingress.class: kong-public
  name: {{ app_name }}-{{ package_name }}-kong
  namespace: {{ namespace }}
spec:
  rules:
    - host: {{ domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ app_name }}-{{ package_name }}-kong
            servicePort: {{ service_port }}
  tls:
    - hosts:
        - {{ domain }}
{% if cert_issuer == 'infra-letsencrypt' %}
      secretName: {{ app_name }}-{{ package_name }}-kong
{% else %}
      secretName: {{ cert_secret }}
{% endif %}
