---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: kong
  name: {{ app_name }}-{{ package_name }}-kong
  namespace: {{ namespace }}
spec:
  rules:
    - host: {{ domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ app_name }}-{{ package_name }}-kong
            servicePort: {{ service_port }}
  tls:
    - hosts:
        - {{ domain }}
      secretName: {{ cert_secret }}
