---
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/plugins: prometheus
  name: {{ app_name }}-{{ package_name }}-kong
  namespace: {{ namespace }}
  labels:
    app: {{ app_name }}
spec:
  ports:
    - name: {{ app_name }}-{{ package_name }}
      protocol: TCP
      port: {{ service_port }}
      targetPort: {{ service_port }}
  selector:
    app: {{ app_name }}-{{ package_name }}
  type: ClusterIP
  sessionAffinity: None
