vault:
  injector:
    registry: registry.sberautotech.ru:5574/infra/docker
    image: vault-injector
    version: latest
  path: "k8s/{{ stand }}"
  role: "{{ stand }}-sa"
  url: https://vault.int.sbauto.tech:8200

k8s_config: '~/.kube/config'
image_pull_secret: docker-registries
deploy_timeout: 300
