vault:
  injector:
    registry: registry.int.sbauto.tech:5574/infra/docker
    image: vault-injector
    version: latest
  path: "k8s/fe-{{ stand }}"
  role: "fe-{{ stand }}-sa"
  url: https://vault.int.sbauto.tech:8200

k8s_config: '~/.kube/config'
image_pull_secret: docker-registries
deploy_timeout: 300
