variables:
  GIT_DEPTH: 10
  DEPLOYER_IMAGE: "${CI_REGISTRY}/infra/docker/deployer:k8s-sat-v2"
  K8S_MANIFESTS_URL: "${CI_SERVER_HOST}/${K8S_MANIFESTS_PATH}/${K8S_MANIFESTS_REPO}.git"
  VERSION: "${CI_COMMIT_BRANCH}-${CI_COMMIT_SHORT_SHA}"
  FRONTEND_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:frontend"
  BACKEND_IMAGE: "${CI_REGISTRY}/${CI_PROJECT_PATH}:backend"
  VAULT_AUTH_ROLE: external-csssr

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" || $CI_PIPELINE_SOURCE == "web"'
      variables:
        DEPLOY_DEV: "true"
        BACKEND_URL: "$BACKEND_DEV_URL"
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_PIPELINE_SOURCE == "web"'
      variables:
        DEPLOY_DEV: "true"
        DEPLOY_PROD: "true"
        BACKEND_URL: "$BACKEND_PROD_URL"

image: "${CI_REGISTRY}/infra/docker/docker:20"

.infra_secrets: &infra_secrets
  secrets:
    PUSH_USER_NAME:
      vault: gitlab/username@secret/gitlab/external/csssr
      file: false
    PUSH_USER_TOKEN:
      vault: gitlab/token@secret/gitlab/external/csssr
      file: false

stages:
  - linters
  - build-backend
  - deploy-backend
  - build-frontend
  - deploy-frontend

.rules_backend_build_template: &rules_backend_build_template
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  rules:
    - changes:
        - backend/**/*

.rules_frontend_build_template: &rules_frontend_build_template
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:backend:
  stage: build-backend
  <<: *rules_backend_build_template
  script:
    - |
      docker build --pull -t ${BACKEND_IMAGE}-${VERSION} --build-arg DOCKER_REGISTRY=${CI_REGISTRY}/infra/docker -f backend/Dockerfile .
      if [ -n "$DEPLOY_DEV" ]; then
        docker push ${BACKEND_IMAGE}-${VERSION}
      fi

build:frontend:
  stage: build-frontend
  <<: *rules_frontend_build_template
  script:
    - |
      docker build --pull --no-cache -t ${FRONTEND_IMAGE}-${VERSION} --build-arg DOCKER_REGISTRY=${CI_REGISTRY}/infra/docker --build-arg BACKEND_API_URL=$BACKEND_URL -f frontend/Dockerfile .
      if [ -n "$DEPLOY_DEV" ]; then
        docker push ${FRONTEND_IMAGE}-${VERSION}
      fi

.deploy_template: &deploy_template
  image: $DEPLOYER_IMAGE
  script:
    - |
      [ -d "${K8S_MANIFESTS_REPO}" ] && rm -rf "${K8S_MANIFESTS_REPO}" || true
      git clone --branch "${K8S_MANIFESTS_BRANCH}" "https://${PUSH_USER_NAME}:${PUSH_USER_TOKEN}@${K8S_MANIFESTS_URL}"
      cd "${K8S_MANIFESTS_REPO}"
      echo -n "${VERSION}" > "${CI_PROJECT_NAME}/${MODULE_NAME}/${STAND}/image_version.txt"
      # Set new image version in override file
      git config --global user.email "${PUSH_USER_EMAIL}"
      git config --global user.name "${PUSH_USER_NAME}"
      git remote set-url origin "https://${PUSH_USER_NAME}:${PUSH_USER_TOKEN}@${K8S_MANIFESTS_URL}"
      git add "${CI_PROJECT_NAME}/${MODULE_NAME}/${STAND}/image_version.txt"
      git commit -m "Auto-push: set ${CI_PROJECT_NAME} image version to ${VERSION}" \
        && git push -u origin "HEAD:${K8S_MANIFESTS_BRANCH}" || true

deploy:backend:dev:
  stage: deploy-backend
  rules:
    - if: '$DEPLOY_DEV == "true"'
      changes:
        - backend/**/*
  variables:
    MODULE_NAME: "backend"
    STAND: "fe-dev"
  <<: *infra_secrets
  <<: *deploy_template

deploy:frontend:dev:
  stage: deploy-frontend
  rules:
    - if: '$DEPLOY_DEV == "true"'
  variables:
    MODULE_NAME: "frontend"
    STAND: "fe-dev"
  <<: *infra_secrets
  <<: *deploy_template

deploy:backend:prod:
  stage: deploy-backend
  rules:
    - if: '$DEPLOY_PROD == "true"'
      changes:
        - backend/**/*
  variables:
    MODULE_NAME: "backend"
    STAND: "infra"
  <<: *infra_secrets
  <<: *deploy_template

deploy:frontend:prod:
  stage: deploy-frontend
  rules:
    - if: '$DEPLOY_PROD == "true"'
      when: manual
  variables:
    MODULE_NAME: "frontend"
    STAND: "infra"
  <<: *infra_secrets
  <<: *deploy_template
